"""Items table changed. Stock table added.

Revision ID: 004db19a84e6
Revises: ba7d3f34175d
Create Date: 2019-11-10 14:53:17.835094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004db19a84e6'
down_revision = 'ba7d3f34175d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('retail_price', sa.Float(precision=2), nullable=False),
    sa.Column('wholesale_price', sa.Float(precision=2), nullable=False),
    sa.Column('discount', sa.Float(precision=2), nullable=True),
    sa.Column('mfd_date', sa.DateTime(), nullable=False),
    sa.Column('exp_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.drop_column('items', 'discount')
    op.drop_column('items', 'qty')
    op.drop_column('items', 'retail_price')
    op.drop_column('items', 'mfd_date')
    op.drop_column('items', 'item_code')
    op.drop_column('items', 'exp_date')
    op.drop_column('items', 'wholesale_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('wholesale_price', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('exp_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('item_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('mfd_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('retail_price', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('discount', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_table('stock')
    # ### end Alembic commands ###
